---
openapi: 3.0.0
info:
  title: Backend Hackthon Agua
  description: Services API - Backend Hackthon Agua
  version: "1.0"
servers:
  - url: http://localhost:6262/api/v1
tags:
  - name: ms-hackthon-agua
    description: Services API - Backend Hackthon Agua


paths:
  /users/login:
    post:
      tags:
        - users
      summary: Login user
      description: Login user
      operationId: loginUser
      requestBody:
        description: User to login
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLoginRequest'
      responses:
        '201':
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserLoginResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conflict'

components:
  schemas:
    BadRequest:
      description: Malformed request
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
    Conflict:
      description: Conflict
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'

    #Request
    UserLoginRequest:
      type: object
      properties:
        email:
          type: string
          description: User email
        password:
          type: string
          description: User password
      required:
        - email
        - password

    #Response
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: "Error message"
        code:
          type: string
          example: "Error"
    SuccessResponse:
      type: object
      properties:
        message:
          type: string
          example: "Success message"
        code:
          type: string
          example: "Success"

    UserLoginResponse:
      type: object
      properties:
        names:
          type: string
          example: "Guillermo"
        last_name:
          type: string
          example: "Santisteban"
        rol:
          type: string
          example: "ADMINISTRADOR"
        token:
          type: string
          example: "123456789"