version: '3'
services:

  agua-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9292:9292"
    container_name: agua-app
    networks:
      - agua

networks:
  agua:
    name: agua-network
